---
# copyright Utrecht University

- name: Ensure Certbot for Let's Encrypt is installed
  ansible.builtin.package:
    name: python-certbot-apache
    state: present


- name: Ensure Apache is stopped
  ansible.builtin.service:
    name: httpd
    state: stopped
  when: not letsencrypt_fullchain.stat.exists


- name: Generate certificate if it  doesn't exist yet
  ansible.builtin.command:
    cmd: "certbot certonly --standalone --noninteractive --agree-tos --email {{ acme_certificates_le_email }} -d {{ epos_msl_fqdn }}"
    creates: "/etc/letsencrypt/live/{{ epos_msl_fqdn }}/fullchain.pem"
  notify: Restart Apache


- name: Add cronjob for Certbot renewal
  ansible.builtin.cron:
    name: Certbot automatic renewal
    job: "sudo certbot renew --quiet --pre-hook 'systemctl stop apache2' --post-hook 'systemctl start apache2'"
    minute: 25
    hour: 0,12


- name: Ensure new certificate is used
  ansible.builtin.copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: '{{ item.mode }}'
    remote_src: true
  with_items:
    - src: '/etc/letsencrypt/live/{{ epos_msl_fqdn }}/fullchain.pem'
      dest: '/etc/ssl/certs/localhost_and_chain.crt'
      mode: '0644'
    - src: '/etc/letsencrypt/live/{{ epos_msl_fqdn }}/fullchain.pem'
      dest: '/etc/ssl/certs/localhost.crt'
      mode: '0644'
    - src: '/etc/letsencrypt/live/{{ epos_msl_fqdn }}/privkey.pem'
      dest: '/etc/ssl/private/localhost.key'
      mode: '0600'
  when: not ansible_check_mode
