# This is a locally modified version of the upstream CKAN docker compose file.

volumes:
  ckan_config:
  ckan_home:
  ckan_storage:
  ckan_coveragedata:
  pg_data:
  solr_data:
  nginx_config:

services:
  ckan:
    container_name: ckan
    image: ghcr.io/utrechtuniversity/cd2-cat-ckan:latest
    links:
      - db
      - solr
      - redis
    depends_on:
      - db
      - solr
      - redis
    ports:
      - "5000"
    environment:
      - CKAN_SQLALCHEMY_URL=postgresql://ckan:${POSTGRES_PASSWORD}@db/ckan_default
      - CKAN_SOLR_URL=http://solr:8983/solr/ckan
      - CKAN_REDIS_URL=redis://redis:6379/1
      - CKAN_SITE_URL=${CKAN_SITE_URL}
      - CKAN_DATABASE_PASSWORD=${CKAN_DATABASE_PASSWORD}
      - CKAN_ADMIN_PASSWORD=${CKAN_ADMIN_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - CD2_HOST=${CD2_HOST}
      - CD2_HOST_PORT=${CD2_HOST_PORT}
      - CKAN_UWSGI_NUM_WORKERS=${CKAN_UWSGI_NUM_WORKERS}
    volumes:
      - ckan_config:/etc/ckan
      - ckan_home:/usr/lib/ckan
      - ckan_storage:/var/lib/ckan

  nginx:
    container_name: nginx
    image: ghcr.io/utrechtuniversity/cd2-cat-nginx:latest
    environment:
      - CD2_HOST=${CD2_HOST}
      - CD2_HOST_PORT=${CD2_HOST_PORT}
      - CKAN_SITE_URL=${CKAN_SITE_URL}
      - CD2_HOST_IP=${CD2_HOST_IP}
      - MTA_ROLE=${MTA_ROLE}
    ports:
      - "${CD2_HOST_IP}:${CD2_HOST_PORT}:443"
    sysctls:
      net.ipv4.ip_unprivileged_port_start: 0
    volumes:
      - nginx_config:/etc/nginx/conf.d
      - ./import-certificates:/etc/import-certificates

  db:
    container_name: db
    image: postgres:12.20
    environment:
      - POSTGRES_DB=ckan_default
      - POSTGRES_USER=ckan
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/db
    volumes:
      - pg_data:/var/lib/postgresql/data

  solr:
    container_name: solr
    image: ghcr.io/utrechtuniversity/cd2-cat-solr:latest
    volumes:
      - solr_data:/var/solr

  redis:
    container_name: redis
    image: redis:6.2

  mta:
    container_name: mta
    image: ghcr.io/utrechtuniversity/cd2-cat-mta:latest
    environment:
      - MTA_ROLE=${MTA_ROLE}
      - POSTFIX_RELAYHOST_FQDN=${POSTFIX_RELAYHOST_FQDN}
      - POSTFIX_RELAYHOST_PORT=${POSTFIX_RELAYHOST_PORT}
      - POSTFIX_RELAYHOST_USERNAME=${POSTFIX_RELAYHOST_USERNAME}
      - POSTFIX_RELAYHOST_PASSWORD=${POSTFIX_RELAYHOST_PASSWORD}
      - POSTFIX_RELAYHOST_AUTH_ENABLED=${POSTFIX_RELAYHOST_AUTH_ENABLED}
      - POSTFIX_RELAYHOST_TLS_ENABLED=${POSTFIX_RELAYHOST_TLS_ENABLED}
      - POSTFIX_MYHOSTNAME=${POSTFIX_MYHOSTNAME}
      - POSTFIX_ORIGIN=${POSTFIX_ORIGIN}
    sysctls:
      net.ipv4.ip_unprivileged_port_start: 0
