- hosts: all

  tasks:
    - name: Update packages
      become: yes
      ansible.builtin.apt:
        update_cache: yes
        upgrade: "yes"

    - name: Install packages
      become: yes
      ansible.builtin.apt:
        name: [git, libpq5, redis-server, nginx, supervisor, postgresql, python3-psycopg2, solr-tomcat, pipenv]
        state: present

    - name: Remove packages
      become: yes
      ansible.builtin.apt:
        name: apache2
        purge: yes
        autoremove: yes
        state: absent

    - name: Get CKAN package
      ansible.builtin.get_url:
        url: https://packaging.ckan.org/python-ckan_2.9-py3-focal_amd64.deb
        dest: /tmp/

    - name: Install CKAN package
      become: yes
      ansible.builtin.apt:
        deb: /tmp/python-ckan_2.9-py3-focal_amd64.deb

    - name: Allow PostgreSQL administrative access from Ansible
      become: yes
      ansible.builtin.lineinfile:
        path: /etc/postgresql/12/main/pg_hba.conf
        regexp: (local   all             postgres                                )peer$
        line: \1trust
        backrefs: yes

    - name: Restart PostgreSQL to effectuate administrative access from Ansible
      become: yes
      ansible.builtin.systemd:
        name: postgresql
        state: reloaded

    - name: Create ckan_default PostgreSQL user
      community.postgresql.postgresql_user:
        name: ckan_default
        password: postgrespass

    - name: Create ckan_default database
      community.postgresql.postgresql_db:
        name: ckan_default
        owner: ckan_default

    - name: Set database, database user and database user password in CKAN config
      become: yes
      ansible.builtin.lineinfile:
        path: /etc/ckan/default/ckan.ini
        regexp: ^(sqlalchemy.url =).*
        line: \1 postgresql://ckan_default:postgrespass@localhost/ckan_default
        backrefs: yes

    - name: Change default Tomcat port
      become: yes
      ansible.builtin.lineinfile:
        path: /etc/tomcat9/server.xml
        regexp: (<Connector port=")8080(" protocol="HTTP/1.1")
        line: \g<1>8983\g<2>
        backrefs: yes

    - name: Replace default Solr schema file
      become: yes
      file:
        src: /usr/lib/ckan/default/src/ckan/ckan/config/solr/schema.xml
        dest: /etc/solr/conf/schema.xml
        state: link
        force: yes

    - name: Restart Tomcat
      become: yes
      ansible.builtin.systemd:
        name: tomcat9
        state: restarted

    - name: Set Solr URL in CKAN config
      become: yes
      ansible.builtin.lineinfile:
        path: /etc/ckan/default/ckan.ini
        regexp: ^#solr_url =.*
        line: solr_url = http://127.0.0.1:8983/solr
        backrefs: yes

    - name: Set site_id in CKAN config
      become: yes
      ansible.builtin.lineinfile:
        path: /etc/ckan/default/ckan.ini
        regexp: ^(ckan.site_id =).*
        line: \1 cd2
        backrefs: yes

    - name: Set site_url in CKAN config
      become: yes
      ansible.builtin.lineinfile:
        path: /etc/ckan/default/ckan.ini
        regexp: ^(ckan.site_url =).*
        line: \1 http://cd2.test
        backrefs: yes

    - name: Initialize CKAN database
      become: yes
      ansible.builtin.command: ckan db init

    - name: Reload Supervisor daemon
      become: yes
      ansible.builtin.command: supervisorctl reload

    - name: Restart Nginx
      become: yes
      ansible.builtin.systemd:
        name: nginx
        state: restarted

    - name: Add default admin user
      become: yes
      ansible.builtin.expect:
        command: ckan -c /etc/ckan/default/ckan.ini sysadmin add admin email=admin@cd2.test name=admin
        responses:
          Create new user: Y
          Password: password
          Repeat for confirmation: password

    - name: Install ckanext-scheming extension
      become: yes
      ansible.builtin.pip:
        name: git+https://github.com/ckan/ckanext-scheming.git#egg=ckanext-scheming
        virtualenv: /usr/lib/ckan/default
        editable: yes

    # An SSH keypair with access to the cd2 repository should be placed in the provisioning/files/
    # directory. The filenames of the keypair files must begin with id_ (e.g. id_rsa + id_rsa.pub).
    # It is recommended, as a security precaution, to generate a dedicated CD² keypair (e.g. using
    # ssh-keygen) and to restrict it's access to the cd2 repository.
    - name: Get filenames of files of SSH keypair to copy
      find:
        paths: files/
        patterns: ^id_
        use_regex: yes
      register: keypair_filenames
      delegate_to: localhost

    - name: Check if keypair files available
      ansible.builtin.fail:
        msg: No keypair files present in provisioning/files/!
      when: not keypair_filenames.files

    - name: Copy SSH keys
      become: yes
      ansible.builtin.copy:
        src: "{{ item.path }}"
        dest: /root/.ssh/
        mode: preserve
      with_items:
        - "{{ keypair_filenames.files }}"

    - name: Add SSH fingerprint of git.science.uu.nl to known_hosts
      become: yes
      shell: ssh-keyscan -H git.science.uu.nl >> /root/.ssh/known_hosts

    - name: Install ckanext-msl_ckan_util repository
      become: yes
      ansible.builtin.pip:
        name: git+ssh://git@git.science.uu.nl/epos-msl/msl_ckan_util.git#egg=ckanext-msl_ckan_util
        virtualenv: /usr/lib/ckan/default
        editable: yes

    - name: Enable ckanext-scheming and ckanext-msl_ckan_util plugins
      become: yes
      ansible.builtin.lineinfile:
        path: /etc/ckan/default/ckan.ini
        backrefs: yes
        regexp: ^(ckan\.plugins = .* recline_view)$
        line: \1 scheming_datasets scheming_groups scheming_organizations msl_custom_facets msl_repeating_fields

    - name: Add ckanext-msl_ckan_util config settings
      become: yes
      ansible.builtin.blockinfile:
        path: /etc/ckan/default/ckan.ini
        block: |
          # msl_ckan_util settings
          ckan.mslfacets.dataset_config = ckanext.msl_ckan_util:samples/facets.json
          ckan.mslindexfields.fields_config = ckanext.msl_ckan_util:samples/msl_index_fields.json

    - name: Reload Supervisor daemon
      become: yes
      ansible.builtin.command: supervisorctl reload

    - name: Restart Nginx
      become: yes
      ansible.builtin.systemd:
        name: nginx
        state: restarted
